# Generated by Django 5.0.6 on 2026-05-11 16:18

import apps.queue.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('description', models.CharField(max_length=200, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Bayram kuni',
                'verbose_name_plural': 'Bayram kunlari',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Terapevt qabuli', max_length=200, verbose_name='Xizmat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_minutes', models.PositiveIntegerField(default=15, help_text='Har bir slot necha daqiqa', verbose_name='Bir mijoz uchun vaqt (daqiqa)')),
                ('icon', models.CharField(default='🏥', help_text='Bitta emoji (masalan 🩺, 📋, 💊)', max_length=10, verbose_name='Emoji belgi')),
                ('color', models.CharField(choices=[('blue', "Ko'k"), ('emerald', 'Yashil'), ('amber', 'Sariq'), ('rose', 'Pushti'), ('violet', 'Binafsha'), ('cyan', 'Moviy')], default='blue', max_length=20, verbose_name='Rang')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('specialty', models.CharField(max_length=200, verbose_name='Mutaxassislik')),
                ('cabinet_number', models.CharField(max_length=20, verbose_name='Kabinet raqami')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Foto')),
                ('bio', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='queue.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('time', models.TimeField(verbose_name='Vaqt')),
                ('queue_number', models.PositiveIntegerField(verbose_name='Navbat raqami')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('called', 'Chaqirildi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('no_show', 'Kelmadi')], default='pending', max_length=20, verbose_name='Holat')),
                ('qr_token', models.CharField(default=apps.queue.models.generate_qr_token, max_length=64, unique=True, verbose_name='QR token')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='queue.doctor', verbose_name='Shifokor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': 'Navbat',
                'verbose_name_plural': 'Navbatlar',
                'ordering': ['-date', 'time'],
                'indexes': [models.Index(fields=['date', 'doctor'], name='queue_appoi_date_e7697b_idx'), models.Index(fields=['user', '-created_at'], name='queue_appoi_user_id_01495c_idx'), models.Index(fields=['status'], name='queue_appoi_status_7110b5_idx')],
                'unique_together': {('doctor', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('start_time', models.TimeField(verbose_name='Ish boshlanishi')),
                ('end_time', models.TimeField(verbose_name='Ish tugashi')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Tushlik boshlanishi')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Tushlik tugashi')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='queue.doctor', verbose_name='Shifokor')),
            ],
            options={
                'verbose_name': 'Ish vaqti',
                'verbose_name_plural': 'Ish vaqtlari',
                'ordering': ['doctor', 'weekday'],
                'unique_together': {('doctor', 'weekday')},
            },
        ),
    ]
